apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: default
spec:
  clusterIP: None
  ports:
  - port: 3306

---
apiVersion: v1
kind: Endpoints
metadata: 
  name: mysql
  namespace: default
subsets:
- addresses:
  - ip: 192.168.220.4
  ports:
  - port: 3306



