apiVersion: v1
kind: Service
metadata:
  name: nacos
spec:
  type: NodePort
  selector:
    app: nacos
  ports:
    - port: 8848

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-config
data:
  mysql.db.name: "nacos"
  mysql.host: "192.168.220.4"
  mysql.port: "3306"
  mysql.user: "root"
  mysql.password: "MyNewPass4!"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nacos
  template:
    metadata:
      labels:
        app: nacos
    spec:
      containers:
      - name: nacos
        image: zhanzixi/nacos-server:1.3.0
        env:
          - name: MODE
            value: standalone
          - name: SPRING_DATASOURCE_PLATFORM
            value: mysql
          - name: MYSQL_SERVICE_DB_NAME
            valueFrom:
              configMapKeyRef:
                name: nacos-config
                key: mysql.db.name
          - name: MYSQL_SERVICE_HOST
            valueFrom:
              configMapKeyRef:
                name: nacos-config
                key: mysql.host
          - name: MYSQL_SERVICE_PORT
            valueFrom:
              configMapKeyRef:
                name: nacos-config
                key: mysql.port
          - name: MYSQL_SERVICE_USER
            valueFrom:
              configMapKeyRef:
                name: nacos-config
                key: mysql.user
          - name: MYSQL_SERVICE_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: nacos-config
                key: mysql.password